# Generated by Django 3.1.7 on 2021-04-01 15:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSchemas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('column_separator', models.CharField(choices=[(',', 'Comma(,)'), (';', 'Semicolon(;)')], default=',', max_length=1)),
                ('string_character', models.CharField(choices=[('"', 'Double-quote(")'), ("'", "Single-quote(')")], default='"', max_length=1)),
                ('modif_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchemaColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.dataschemas')),
            ],
            options={
                'unique_together': {('schema', 'order'), ('schema', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CompanyColumn',
            fields=[
                ('schemacolumn_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schemas.schemacolumn')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('schemas.schemacolumn',),
        ),
        migrations.CreateModel(
            name='FullNameColumn',
            fields=[
                ('schemacolumn_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schemas.schemacolumn')),
                ('first_name', models.CharField(blank=True, max_length=10, null=True)),
                ('last_name', models.CharField(blank=True, max_length=15, null=True)),
            ],
            bases=('schemas.schemacolumn',),
        ),
        migrations.CreateModel(
            name='IntegerColumn',
            fields=[
                ('schemacolumn_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schemas.schemacolumn')),
                ('range_low', models.IntegerField(blank=True, default=-20, null=True)),
                ('range_high', models.IntegerField(blank=True, default=40, null=True)),
            ],
            bases=('schemas.schemacolumn',),
        ),
        migrations.CreateModel(
            name='JobColumn',
            fields=[
                ('schemacolumn_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schemas.schemacolumn')),
                ('job_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('schemas.schemacolumn',),
        ),
        migrations.CreateModel(
            name='PhoneColumn',
            fields=[
                ('schemacolumn_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schemas.schemacolumn')),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
            bases=('schemas.schemacolumn',),
        ),
    ]
